name: Deploy AWS Microservices and Terraform

on:
  push:
    branches:
      - main
  
permissions:
  id-token: write
  contents: read 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'us-east-2'
      LAMBDA_FUNCTION_CRYPTO_PRICE: 'email_crypto_price_function'
      LAMBDA_FUNCTION_SEARCH_HISTORY: 'get_search_history_function'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Build and zip crypto price lambda
        working-directory: ./lambda/email_crypto_price
        run: |
          npm run gitHubActionsBuild

      - name: Build and zip search history lambda
        working-directory: ./lambda/get_search_history
        run: |
          npm run gitHubActionsBuild

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::006015593052:role/github-assume-role-for-terraform
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve